package cs505.group1.state;

/**
 * A framework for developing and using contexts in a finite state machine
 * to set actions generated by a GrovePi button sensor.
 * This class can be used as provided for a single context, or extended into 
 * multiple contexts for additional flexibility. 
 * 
 * 
 * @author CS505 Fall17 Group1: <br>
 * Emily Park, Jeffrey Blankenship, Cecelia Oluwadoyinsola, James Luczynski, Melissa Mulcahy <br>
 * @version 2017.11.15
 */
public class MirrorContext extends ButtonContext{

    public MirrorContext(ButtonState buttonState) {
        super(buttonState);
        this.buttonState = buttonState;
    }
    
    
    /**
     * Invokes the toString method of the concrete class for the
     * current state.  
     * @return String
     */
    @Override
    public String toString(){
        return this.buttonState.toString();
    };
}
